name: Compile Paper

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: paper.tex
          latexmk_shell_escape: true
          extra_system_packages: "py-pygments"

      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: paper
          path: ./paper.pdf
