name: Compile Dissertation

on: [ push ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: proposal.tex
          latexmk_shell_escape: true

      - uses: actions/upload-artifact@v2
        if: success()
        with:
          name: dissertation
          path: ./proposal.pdf
