on: push

name: Continuous Integration

env:
  BUILD_TYPE: Release

jobs:
  ci:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Clang and Boost development Libraries
        run: sudo apt-get install clang libclang-dev libboost-dev libgtest-dev

      - name: Create Build Environment
        run: cmake -E make_directory ${{runner.workspace}}/build

      - name: Configure CMake
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake $GITHUB_WORKSPACE -DCMAKE_BUILD_TYPE=$BUILD_TYPE

      - name: Build
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: cmake --build . --config $BUILD_TYPE

      - name: Test
        working-directory: ${{runner.workspace}}/build
        shell: bash
        run: ./test/runTests

      - uses: actions/upload-artifact@v2
        with:
          name: ptr-tidy
          path: ${{runner.workspace}}/build/ptr-tidy
